### ISSUE TITLE
Q[1,f] - Query testing, optimization and verification

### ISSUE THREAD

**Issue by AviKatziuk** [amosproj/amos2023ws05-pipeline-config-chat-ai#53]
## User story
1. As SDs.
2. We want to test and improve the bot's capabilities.
3. So that it can successfully handle a wide range of requests.

## Q[1,f]

create an rtdip-sdk pipeline configuration that Retrieves temperature data from a REST API, normalize the data, and write it into a MongoDB collection

## Acceptance criteria
1. Run the query and document the given output and response speed.
2. If you think the query is correct, send it to Shell.
3. If the query is incorrect, edit the RAG to improve the results.
4. **If the changes to the RAG are large enough to constitute a defined task, talk to Avi to set up one on the board.**
5.  After you receive the response from Shell:
6.  If the query passes, the task is complete.
7.  If the query fails, adjust the RAG and send the query to Shell again.
8. **In case the RAG was changed at any point:** Test and make sure the changes don't adversely affect other related queries.

## Definition of done (DoD)
Feature DoD:

1. Code review has been completed and code has been merged.
2. User interaction tests pass on all major browsers.

Sprint Release DoD:

1. Project builds, deploys, and tests successfully.

Project Release Definition of Done

1. User interaction tests pass on all major browsers.
2. Design documentation has been updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner-approved features
* All tests are passing
* Developers agreed to release

## Why do we have one task per test?
Our project has mainly two capabilities: The variety of actions supported by the bot and the variety of natural text input our bot is capable of understanding to perform requested actions.
Each test query is a combination of one action and one manner of requesting this action in natural language. 
Since these are our main two concerns, we consider each verified query as a feature and therefore each feature gets its own testing task.

**Comment by Obismadi99** [comment]
```python
from rtdip.sdk.components import RESTAPISource, NormalizationTransformer, MongoDBDestination
from rtdip.sdk.pipelines import Pipeline

# Define the pipeline
pipeline = Pipeline()

# Add the components to the pipeline
pipeline.add_component(RESTAPISource(
    url='https://api.example.com/temperature',
    headers={'Authorization': 'Bearer <API_KEY>'}
))

pipeline.add_component(NormalizationTransformer(
    normalization_factor=0.5
))

pipeline.add_component(MongoDBDestination(
    uri='mongodb://localhost:27017',
    database='mydatabase',
    collection='temperature_data'
))

# Execute the pipeline
pipeline.execute()
``` 

Looks good

**Comment by lyndanajjar** [comment]
```from rtdip.pipeline import Pipeline
from rtdip.pipeline.sources.rest import RESTSource
from rtdip.pipeline.transformers import FunctionTransformer
from rtdip.pipeline.destinations.mongo import MongoDestination

# Define the pipeline configuration
pipeline_config = {
    "sources": [
        {
            "name": "TemperatureAPI",
            "source": RESTSource,
            "args": {
                "url": "https://api.example.com/temperature",
                "headers": {
                    "API-Key": "YOUR_API_KEY"
                }
            }
        }
    ],
    "transformers": [
        {
            "name": "NormalizeTemperature",
            "transformer": FunctionTransformer,
            "args": {
                "function": lambda temperature: (temperature - 32) * 5/9
            }
        }
    ],
    "destinations": [
        {
            "name": "TemperatureCollection",
            "destination": MongoDestination,
            "args": {
                "url": "mongodb://localhost:27017",
                "database": "mydb",
                "collection": "temperature"
            }
        }
    ]
}

# Create the pipeline
pipeline = Pipeline.from_config(pipeline_config)

# Run the pipeline
pipeline.run()

``` 
When I tried it , there is no sparksession "    spark = SparkSessionUtility(config={}).execute()"
