### ISSUE TITLE
Initialize and test Q3 queries manually with PyTest 🦘

### ISSUE THREAD

**Issue by AviKatziuk** [amosproj/amos2023ws05-pipeline-config-chat-ai#69]
## User story
1. As SDs.
3. We want to test our queries by ourselves.
4. So that we can do it quicker, without the need to trouble Shell.

## Acceptance criteria
1. Initialize testing via PyTest, based on the test files in the RTDIP repo.
2. Test manually the queries of week 3 with PyTest.
3. Document the results.
4. Update on your progress in the internal testing channel on Slack.
5. Bonus: research how we can automate the tests

## Definition of done (DoD)
Feature DoD:

1. Code review has been completed and code has been merged.
2. User interaction tests pass on all major browsers.

Sprint Release DoD:

1. Project builds, deploys, and tests successfully.

Project Release Definition of Done

1. User interaction tests pass on all major browsers.
2. Design documentation has been updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Nahrain1** [comment]
[Pytest Results for week 3](https://www.notion.so/5654c03052b145198565242c61ffdcc8?v=d5b0f5b6a29542b28cf3dd600a6d840b&p=fb871f5248b741bc95361615b5a6c198&pm=s)
