### ISSUE TITLE
Solution #2: Retrievers merger 👣

### ISSUE THREAD

**Issue by AviKatziuk** [amosproj/amos2023ws05-pipeline-config-chat-ai#80]
## User story
1. As SDs.
2. We want to try a different approach for the RAG.
3. So that the output can be more accurate.

## Acceptance criteria
1. Explore the solution of merging retrievers 
2. If it seems viable, attempt to implement it.
3. (If solution 1 of the lean content hub is ready, you can consider trying using that as a content hub)
4. (Testing task is separate)

## Definition of done (DoD)
Feature DoD:

1. Code review has been completed and code has been merged.
2. User interaction tests pass on all major browsers.

Sprint Release DoD:

1. Project builds, deploys, and tests successfully.

Project Release Definition of Done

1. User interaction tests pass on all major browsers.
2. Design documentation has been updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by ceciliabetb** [comment]
Est. remaining = 5

**Comment by ceciliabetb** [comment]
Real remaining 5.
